export const USER_CALENDAR = [
  {
    days: [
      {
        date: "2025-09-01",
        workDay: true,
        normHours: 8,
        dayOfWeek: "MONDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-02",
        workDay: true,
        normHours: 8,
        dayOfWeek: "TUESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-03",
        workDay: true,
        normHours: 8,
        dayOfWeek: "WEDNESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-04",
        workDay: true,
        normHours: 8,
        dayOfWeek: "THURSDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-05",
        workDay: true,
        normHours: 8,
        dayOfWeek: "FRIDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-06",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SATURDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-07",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SUNDAY",
        availableChoiceOfOvertimeType: [],
      },
    ],
  },
  {
    days: [
      {
        date: "2025-09-08",
        workDay: true,
        normHours: 8,
        dayOfWeek: "MONDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-09",
        workDay: true,
        normHours: 8,
        dayOfWeek: "TUESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-10",
        workDay: true,
        normHours: 8,
        dayOfWeek: "WEDNESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-11",
        workDay: true,
        normHours: 8,
        dayOfWeek: "THURSDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-12",
        workDay: true,
        normHours: 8,
        dayOfWeek: "FRIDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-13",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SATURDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-14",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SUNDAY",
        availableChoiceOfOvertimeType: [],
      },
    ],
  },
  {
    days: [
      {
        date: "2025-09-15",
        workDay: true,
        normHours: 8,
        dayOfWeek: "MONDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-16",
        workDay: true,
        normHours: 8,
        dayOfWeek: "TUESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-17",
        workDay: true,
        normHours: 8,
        dayOfWeek: "WEDNESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-18",
        workDay: true,
        normHours: 8,
        dayOfWeek: "THURSDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-19",
        workDay: true,
        normHours: 8,
        dayOfWeek: "FRIDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-20",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SATURDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-21",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SUNDAY",
        availableChoiceOfOvertimeType: [],
      },
    ],
  },
  {
    days: [
      {
        date: "2025-09-22",
        workDay: true,
        normHours: 8,
        dayOfWeek: "MONDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-23",
        workDay: true,
        normHours: 8,
        dayOfWeek: "TUESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-24",
        workDay: true,
        normHours: 8,
        dayOfWeek: "WEDNESDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-25",
        workDay: true,
        normHours: 8,
        dayOfWeek: "THURSDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-26",
        workDay: true,
        normHours: 8,
        dayOfWeek: "FRIDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-27",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SATURDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-28",
        workDay: false,
        normHours: 0,
        dayOfWeek: "SUNDAY",
        availableChoiceOfOvertimeType: [],
      },
    ],
  },
  {
    days: [
      {
        date: "2025-09-29",
        workDay: true,
        normHours: 8,
        dayOfWeek: "MONDAY",
        availableChoiceOfOvertimeType: [],
      },
      {
        date: "2025-09-30",
        workDay: true,
        normHours: 8,
        dayOfWeek: "TUESDAY",
        availableChoiceOfOvertimeType: [],
      },
    ],
  },
];

export const PROJECT_ASSIGNMENTS = [
  {
    id: "TJAS-2",
    name: "TJAS-2",
    type: "npa",
    tasks: [
      {
        id: "group-54708-4060741400394176500",
        name: "TJAS-2",
        billable: false,
        excludeHours: false,
        restrictedOvt: true,
        timePackageId: 54708,
        timeLocks: [
          {
            date: "2025-09-01",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-02",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-03",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-04",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-05",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-06",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-07",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-08",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-09",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-10",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-11",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-12",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-13",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-14",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-15",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-16",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-17",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-18",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-19",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-20",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-21",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-22",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-23",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-24",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-25",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-26",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-27",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-28",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-29",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-30",
            locks: "",
            locked: false,
          },
          {
            date: "2025-09-31",
            locks: "",
            locked: false,
          },
        ],
        activities: [],
        predefinedActivities: [],
      },
    ],
    timeLocks: [
      {
        date: "2025-08-01",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-02",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-03",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-04",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-05",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-06",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-07",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-08",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-09",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-10",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-11",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-12",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-13",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-14",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-15",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-16",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-17",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-18",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-19",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-20",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-21",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-22",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-23",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-24",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-25",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-26",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-27",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-28",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-29",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-30",
        locks: "",
        locked: false,
      },
      {
        date: "2025-08-31",
        locks: "",
        locked: false,
      },
    ],
    preCalculatedReportedHours: [
      {
        date: "2025-09-01",
        duration: 2,
        overtimeDuration: 0,
      },
      {
        date: "2025-09-03",
        duration: 2,
        overtimeDuration: 0,
      },
    ],
    markedWorklogInfo: null,
    statusConfigInfo: null,
    canViewProjectDetails: false,
    hasPermissionToEdit: true,
    hasPermissionToApproveOvertime: false,
    detailsConcealed: false,
    alwaysShowTotalSum: true,
    hasPermissionToViewPackages: false,
    hasPermissionToReportingLock: false,
    hasPermissionToReportingUnlock: false,
    hasPermissionToBillingLock: false,
    hasPermissionToBillingUnlock: false,
    hasPermissionToRequestBillingUnlock: true,
    hasPermissionToEditOutOfAssignment: true,
    restrictedOvt: true,
    canManageWorklogs: true,
    canEditOvertime: true,
    canPrefillWorklogs: true,
    billingLockDay: "2025-08-31",
    billingLimitDay: "2025-10-29",
    billingPastLimitDay: "2025-08-31",
    reportingLimitDay: "2025-10-29",
    reportingLockDay: "2025-08-31",
    pmc: false,
  },
  {
    id: "Demo",
    name: "Demo",
    type: null,
    tasks: [
      {
        id: "124315-620890479",
        name: "Demo Task",
        billable: true,
        excludeHours: false,
        restrictedOvt: false,
        timePackageId: 124315,
        timeLocks: [
          {
            date: "2025-08-01",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-02",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-03",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-04",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-05",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-06",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-07",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-08",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-09",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-10",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-11",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-12",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-13",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-14",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-15",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-16",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-17",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-18",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-19",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-20",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-21",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-22",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-23",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-24",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-25",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-26",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-27",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-28",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-29",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-30",
            locks: "",
            locked: false,
          },
          {
            date: "2025-08-31",
            locks: "",
            locked: false,
          },
        ],
        activities: [
          {
            name: "ADNO-TAMS",
            pinned: true,
            predefinedActivityId: null,
            worklogs: [
              {
                id: 184797579,
                overtimeId: null,
                date: "2025-08-01",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 184931666,
                overtimeId: null,
                date: "2025-08-04",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185032288,
                overtimeId: null,
                date: "2025-08-05",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185093727,
                overtimeId: null,
                date: "2025-08-06",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185147483,
                overtimeId: null,
                date: "2025-08-07",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185187643,
                overtimeId: null,
                date: "2025-08-08",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185312635,
                overtimeId: null,
                date: "2025-08-11",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185406397,
                overtimeId: null,
                date: "2025-08-12",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185453667,
                overtimeId: null,
                date: "2025-08-13",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185498533,
                overtimeId: null,
                date: "2025-08-14",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
              {
                id: 185547117,
                overtimeId: null,
                date: "2025-08-15",
                duration: 8,
                overtimeStatus: null,
                overtimeType: null,
                overtimeTitle: null,
                version: "1573abd5db16c93a2878d09fdcd5f3de",
                overtimeLock: null,
                editableOvertime: null,
                markupStatusLock: false,
                attachments: [],
                externalWorklog: false,
              },
            ],
          },
        ],
        predefinedActivities: [],
      },
    ],
    timeLocks: [
      {
        date: "2025-08-01",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-02",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-03",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-04",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-05",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-06",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-07",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-08",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-09",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-10",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-11",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-12",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-13",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-14",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-15",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-16",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-17",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-18",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-19",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-20",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-21",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-22",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-23",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-24",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-25",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-26",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-27",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-28",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-29",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-30",
        locks: "b",
        locked: true,
      },
      {
        date: "2025-08-31",
        locks: "b",
        locked: true,
      },
    ],
    preCalculatedReportedHours: [
      {
        date: "2025-09-02",
        duration: 8,
        overtimeDuration: 0,
      },
    ],
    markedWorklogInfo: null,
    statusConfigInfo: null,
    canViewProjectDetails: false,
    hasPermissionToEdit: true,
    hasPermissionToApproveOvertime: false,
    detailsConcealed: false,
    alwaysShowTotalSum: true,
    hasPermissionToViewPackages: false,
    hasPermissionToReportingLock: false,
    hasPermissionToReportingUnlock: false,
    hasPermissionToBillingLock: false,
    hasPermissionToBillingUnlock: false,
    hasPermissionToRequestBillingUnlock: true,
    hasPermissionToEditOutOfAssignment: true,
    restrictedOvt: false,
    canManageWorklogs: true,
    canEditOvertime: true,
    canPrefillWorklogs: true,
    billingLockDay: "2025-08-31",
    billingLimitDay: "2025-10-29",
    billingPastLimitDay: "2025-08-31",
    reportingLimitDay: "2025-10-29",
    reportingLockDay: "2025-08-31",
    pmc: false,
  },
];
